### ISSUE TITLE
RemoteData mapSuccess type is unexpected

### ISSUE THREAD

**Issue by ohanhi** [klemola/matiasklemola.com#9]
I just copied over your RemoteData.ts implementation to our project, and happened to notice that the type of `mapSuccess` is a little strange:

```typescript
mapSuccess<T>(fn: (data: T) => any, remoteData: Success<T>): Success<T>
```

Mapping functions usually are able to alter the type within the functor, right? As in, `map : (a -> b) -> List a -> List b`. This type we have for `mapSuccess` assumes we always have the same inner type before and after the mapping. I'd suggest changing the definition of this function to something like this:

```typescript
mapSuccess<T, U>(fn: (data: T) => U, remoteData: Success<T>): Success<U>
```

Anyways, thanks for publishing this variant of the RemoteData pattern. This feels much more readable to me than the most popular alternatives! :+1:

**Comment by klemola** [comment]
You are absolutely correct. I reckon folks want to use `mapSuccess` for something else than just replacing a number with another number. Thanks for pointing that out!

I've updated the source code.
